IOU no longer calculated by division by 0 from p1.union(p2).area
error:iou = p1.intersection(p2).area/ p1.union(p2).area
ZeroDivisionError: float division by zero